apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: WebApp-pvc
  namespace: WebApp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: postgres-data
    namespace: WebApp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

        #---

#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: nginx-pvc
#  namespace: WebApp
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 500Mi
