apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: microblog
spec:
  selector:
    app: auth
  ports:
    - name: http
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: microblog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: YOUR_REGISTRY/auth-service:latest
          ports:
            - containerPort: 5000
          env:
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: microblog-secrets
                  key: AUTH_SECRET
            - name: DATABASE_URL
              value: postgresql+psycopg2://app:app@db:5432/microblog
            - name: COOKIE_DOMAIN
              value: ""
          readinessProbe:
            httpGet:
              path: /whoami
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 6

